# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 32deb9d59782fe305e0c77044530510521d1068b7cb04e67d33b487d9d1dc362df1d4aaeb50525fb7de7c9f794a254eb80af8f083ec7d3d2d2863fd0ebbd33e0

test:
  secret_key_base: bd640edbb516857be0ba8bb1d708e1945ce1a399b700ef49677f8165462bda65adb204456e531270dfa0623c89c53b2c82c0b536d557131ee422562c591b3546

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
